---

R1:
    hostname: "192.168.179.130"
    username: "ray" 
    password: "cisco"
    port: 22
    groups:
        - cisco_group
#        - south

R2:
    hostname: "192.168.179.131"
    username: "ray" 
    password: "cisco"
    port: 22
    groups:
        - cisco_group
#        - north
R3:
    hostname: "192.168.179.132"
    username: "ray" 
    password: "cisco"
    port: 22
    groups:
        - cisco_group
#        - south

R4: 
    hostname: "192.168.179.133"
    username: "ray" 
    password: "cisco"
    port: 22
    groups:
        - cisco_group
#        - north

#R5:
#    hostname: "192.168.179.134"
#    groups:
#        - cisco_group
#        - north

#R6:
#    hostname: "192.168.179.135"
#    groups:
#        - cisco_group
#        - south

#R7:
#    hostname: "192.168.179.136"
#    groups:
#        - cisco_group
#        - north
