---

R1:
    hostname: "192.168.179.130"
    groups:
        - cisco_group

R2:
    hostname: "192.168.179.131"
    groups:
        - cisco_group
                
R3:
    hostname: "192.168.179.132"
    groups:
        - cisco_group
        
R4: 
    hostname: "192.168.179.133"
    groups:
        - cisco_group

R5:
    hostname: "192.168.179.134"
    groups:
        - cisco_group


R6:
    hostname: "192.168.179.135"
    groups:
        - cisco_group


R7:
    hostname: "192.168.179.136"
    groups:
        - cisco_group
