OSPF:
    process_id: "1" 
    rid: "1.1.1.1"
    redistributing:
        - "connected subnets"
        - "eigrp 43 subnets"
    networks:
        - "1.1.1.1 0.0.0.0 area 0"
        - "10.0.0.0 0.0.0.0 area 1"

ACCESS_LISTS: 
    ACL1:
       - "permit ip host 1.1.1.1 host 8.8.8.8"
       - "deny icmp any any"

    ACL2: 
        - "permit tcp host 1.2.3.4 any eq 22"
        - "permit icmp host 2.3.4.5 any"
        - "deny ip any any"

NTP: 
    update_calendar: True 
    servers:
        - "1.1.1.1 prefer"
        - "11.11.11.11"