OSPF:
    process_id: "3" 
    rid: "3.3.3.3"
    redistributing:
        - "connected subnets"
        - "eigrp 22 subnets"
    networks:
        - "3.3.3.3 0.0.0.0 area 0"
        - "10.0.0.0 0.0.0.0 area 3"

ACCESS_LISTS: 
    ACL1:
       - "permit ip host 2.2.2.2 host 3.3.3.3"
       - "deny icmp any any"

    ACL2: 
        - "permit tcp host 4.3.2.1 any eq 22"
        - "permit icmp host 9.9.9.9 any"
        - "deny ip any host 8.8.8.8"

NTP:
    update_calendar: True
    servers:
        - "2.2.2.2 prefer"
        - "22.22.22.22"
        - "8.8.8.8"