---

R1:
    hostname: 192.168.179.130
    platform: 'ios'
    username: ray
    password: cisco
    groups:
        - cisco_group
    data:
        country: usa
        region: north
        state: washington
        coast: west

R2:
    hostname: 192.168.179.131
    platform: 'ios'
    username: ray 
    password: cisco 
    groups:
        - cisco_group
    data: 
        country: usa 
        region: north
        state: montana
        coast: west 

R3:
    hostname: 192.168.179.132
    platform: 'ios'
    username: ray
    password: cisco
    groups:
        - cisco_group
    data:
        country: usa
        region: north
        state: michigan

R4:
    hostname: 192.168.179.133
    platform: 'ios'
    username: ray 
    password: cisco 
    groups:
        - cisco_group
    data: 
        country: usa 
        region: north
        state: new york

R5:
    hostname: 192.168.179.134
    platform: 'ios'
    username: ray
    password: cisco
    groups:
        - cisco_group
    data:
        country: usa
        region: south
        state: california
        coast: west

R6:
    hostname: 192.168.179.135 
    platform: 'ios'
    username: ray
    password: cisco
    groups:
        - cisco_group
    data: 
        country: usa 
        region: south 
        state: arizona
        coast: west 

R7:
    hostname: 192.168.179.136
    platform: 'ios'
    username: ray
    password: cisco
    groups:
        - cisco_group
    data:
        country: usa 
        region: south 
        state: florida
