---

R1:
    hostname: 192.168.179.130
    groups:
#        - grand_slam_winner
#        - athlete 
#        - famous 
#        - human
#    data:
#        sex: male 
#        age: 44
#        married: False

R2:
    hostname: 192.168.179.131
    groups:
#        - actress 
#        - famous
#        - human
#    data: 
#        sex: female 
#        age: 70
#        married: True 

R3:
    hostname: 192.168.179.132
    groups:
#        - tennis_player
#        - athlete
#        - famous 
#        - human 
#    data:
#        sex: male
#        age: 32
#        married: True

R4:
    hostname: 192.168.179.133
    groups:
#        - non-human
#        - famous
#    data: 
#        sex: male
#        age: 17
#        married: False

#R5:
#    hostname: 192.168.179.134
#    groups:
#        - famous 
#        - human 
#        - nobel_prize_winner
#    data:
#        sex: female
#        age: 144
#        married: True

#R6:
#    hostname: 192.168.179.135 
#    groups:
#        - famous
#        - non-human
#    data: 
#        sex: female
#        age: 9
#        married: False 

#R7:
#    hostname: 192.168.179.136
#    groups:
#        - grand_slam_winner
#        - tennis_player
#        - athlete
#        - famous
#        - human
#    data:
#        sex: male
#        age: 38
#        married: True
